description = "Ubuntu 24.04 Noble Numbat base image with buildpacks for Apt, Java, Go, Node.js, Python, .NET and Procfile"

[build]
  image = "docker.io/paketobuildpacks/ubuntu-noble-build:0.0.73"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/apt:0.1.0"
  version = "0.1.0"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/java-native-image:14.3.0"
  version = "14.3.0"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/java:21.4.0"
  version = "21.4.0"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/go:4.19.7"
  version = "4.19.7"

[[buildpacks]]
  uri = "docker://docker.io/rainbond/nodejs:10.0.3"
  version = "10.0.3"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/python:2.44.1"
  version = "2.44.1"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/dotnet-core:4.2.2"
  version = "4.2.2"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/procfile:5.13.1"
  version = "5.13.1"

[lifecycle]
  version = "0.21.6"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/apt"
    version = "0.1.0"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/java-native-image"
    version = "14.3.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/apt"
    version = "0.1.0"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/java"
    version = "21.4.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/apt"
    version = "0.1.0"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/go"
    version = "4.19.7"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/apt"
    version = "0.1.0"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/nodejs"
    version = "10.0.3"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/apt"
    version = "0.1.0"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/python"
    version = "2.44.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/apt"
    version = "0.1.0"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/dotnet-core"
    version = "4.2.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/apt"
    version = "0.1.0"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "5.13.1"

[run]

  [[run.images]]
    image = "docker.io/paketobuildpacks/ubuntu-noble-run:latest"

[stack]
  id = "io.buildpacks.stacks.noble"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
